#include "Plans/SingleAgent/InteractWithPlayground1534836538908.h"
using namespace alica;
/*PROTECTED REGION ID(eph1534836538908) ENABLED START*/ //Add additional using directives here
#include <wumpus/WumpusWorldModel.h>
#include <WumpusEnums.h>
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:InteractWithPlayground

    /* generated comment
     
     Task: DefaultTask  -> EntryPoint-ID: 1534836538910

     */
    shared_ptr<UtilityFunction> UtilityFunction1534836538908::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1534836538908) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

    //State: Wait in Plan: InteractWithPlayground

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : your turn msg received 
     *
     * Plans in State: 				
     *   - Plan - (Name): WaitForTurnDefault, (PlanID): 1534835374750 
     *
     * Tasks: 
     *   - DefaultTask (1414681164704) (Entrypoint: 1534836538910)
     *
     * States:
     *   - Wait (1534836538909)
     *   - MyTurn (1534836578485)
     *
     * Vars:
     */
    bool TransitionCondition1534836595527::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1534836594030) ENABLED START*/
        auto turnInfo = this->wm->wumpusSimData.getIsMyTurnBuffer()->getLastValidContent();
        if (turnInfo != nonstd::nullopt)
        {
            if (*turnInfo) //&& this->wm->wumpusSimData.getIntegratedFromSimulator()
            //&& this->wm->wumpusSimData.isIntegratedFromAllAgents())
            {
                return true;
            }
        }
        return false;
        /*PROTECTED REGION END*/

    }

    //State: MyTurn in Plan: InteractWithPlayground

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : any child success 
     *
     * Plans in State: 				
     *   - Plan - (Name): NextAction, (PlanID): 1554202530131 
     *
     * Tasks: 
     *   - DefaultTask (1414681164704) (Entrypoint: 1534836538910)
     *
     * States:
     *   - Wait (1534836538909)
     *   - MyTurn (1534836578485)
     *
     * Vars:
     */
    bool TransitionCondition1534836628585::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1534836627481) ENABLED START*/
        return rp->isAnyChildStatus(PlanStatus::Success);
        /*PROTECTED REGION END*/

    }

}
