#include "Plans/SingleAgent/MyTurn1534836685239.h"
using namespace alica;
/*PROTECTED REGION ID(eph1534836685239) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:MyTurn

    //Check of RuntimeCondition - (Name): NewRuntimeCondition, (ConditionString): , (Comment) :  

    /* 
     * Available Vars:
     *	- MyTurnPlanVar (1534925430550)
     */
    bool RunTimeCondition1534925376501::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1534925376501) ENABLED START*/
        return true;
        /*PROTECTED REGION END*/
    }

    /* generated comment
     
     Task: DefaultTask  -> EntryPoint-ID: 1534836698774

     */
    shared_ptr<UtilityFunction> UtilityFunction1534836685239::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1534836685239) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

    //State: PerformAction in Plan: MyTurn

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : any child success  
     *
     * Plans in State: 				
     *   - Plan - (Name): PerformActionDefault, (PlanID): 1534836780649 
     *
     * Tasks: 
     *   - DefaultTask (1414681164704) (Entrypoint: 1534836698774)
     *
     * States:
     *   - PerformAction (1534836698773)
     *   - ActionPerformed (1534836725909)
     *
     * Vars:
     */
    bool TransitionCondition1534836737992::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1534836736600) ENABLED START*/
        return rp->isAnyChildStatus(PlanStatus::Success);
        /*PROTECTED REGION END*/

    }

//State: ActionPerformed in Plan: MyTurn

}
