#include "Plans/SingleAgent/NextAction1554202530131.h"
using namespace alica;
/*PROTECTED REGION ID(eph1554202530131) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:NextAction

    /* generated comment
     
     Task: DefaultTask  -> EntryPoint-ID: 1554202530133

     */
    shared_ptr<UtilityFunction> UtilityFunction1554202530131::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1554202530131) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

    //State: DetermineObjective in Plan: NextAction

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : determine obj success 
     *
     * Plans in State: 				
     *   - Plan - (Name): DetermineObjectiveDefault, (PlanID): 1554202577790 
     *
     * Tasks: 
     *   - DefaultTask (1414681164704) (Entrypoint: 1554202530133)
     *
     * States:
     *   - DetermineObjective (1554202530132)
     *   - PlanAndExecute (1554202945017)
     *   - Success (1554202959483)
     *
     * Vars:
     */
    bool TransitionCondition1554202971930::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1554202970601) ENABLED START*/
        return rp->isAnyChildStatus(PlanStatus::Success);
        /*PROTECTED REGION END*/

    }

    //State: PlanAndExecute in Plan: NextAction

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : success 
     *
     * Plans in State: 				
     *   - Plan - (Name): PerformActionDefault, (PlanID): 1534836780649 
     *
     * Tasks: 
     *   - DefaultTask (1414681164704) (Entrypoint: 1554202530133)
     *
     * States:
     *   - DetermineObjective (1554202530132)
     *   - PlanAndExecute (1554202945017)
     *   - Success (1554202959483)
     *
     * Vars:
     */
    bool TransitionCondition1554203054731::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1554203053575) ENABLED START*/
        return rp->isAnyChildStatus(PlanStatus::Success);
        /*PROTECTED REGION END*/

    }

//State: Success in Plan: NextAction

}
