#include "Plans/SingleAgent/Planning1551262808911.h"
using namespace alica;
/*PROTECTED REGION ID(eph1551262808911) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:Planning

    /* generated comment
     
     Task: DefaultTask  -> EntryPoint-ID: 1551262808913

     */
    shared_ptr<UtilityFunction> UtilityFunction1551262808911::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1551262808911) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

    //State: DetermineGoal in Plan: Planning

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : goal found 
     *
     * Plans in State: 				
     *   - Plan - (Name): DetermineGoalDefault, (PlanID): 1551695076041 
     *
     * Tasks: 
     *   - DefaultTask (1414681164704) (Entrypoint: 1551262808913)
     *
     * States:
     *   - DetermineGoal (1551262808912)
     *   - EvaluateGoal (1551262842117)
     *   - PlanActions (1551263139139)
     *   - EvaluateActions (1551263260517)
     *   - Perform Action (1551263346551)
     *
     * Vars:
     */
    bool TransitionCondition1551263121075::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1551263120298) ENABLED START*/
        return false;
        /*PROTECTED REGION END*/

    }

    //State: EvaluateGoal in Plan: Planning

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : goal valid 
     *
     * Plans in State: 				
     *   - Plan - (Name): EvaluateGoalDefault, (PlanID): 1551695098593 
     *
     * Tasks: 
     *   - DefaultTask (1414681164704) (Entrypoint: 1551262808913)
     *
     * States:
     *   - DetermineGoal (1551262808912)
     *   - EvaluateGoal (1551262842117)
     *   - PlanActions (1551263139139)
     *   - EvaluateActions (1551263260517)
     *   - Perform Action (1551263346551)
     *
     * Vars:
     */
    bool TransitionCondition1551263161484::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1551263159876) ENABLED START*/
        return false;
        /*PROTECTED REGION END*/

    }

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : goal not safely reachable && other fields safely reachable || haveGold && goal not start field || glitter known && goal not gold field 
     *
     * Plans in State: 				
     *   - Plan - (Name): EvaluateGoalDefault, (PlanID): 1551695098593 
     *
     * Tasks: 
     *   - DefaultTask (1414681164704) (Entrypoint: 1551262808913)
     *
     * States:
     *   - DetermineGoal (1551262808912)
     *   - EvaluateGoal (1551262842117)
     *   - PlanActions (1551263139139)
     *   - EvaluateActions (1551263260517)
     *   - Perform Action (1551263346551)
     *
     * Vars:
     */
    bool TransitionCondition1551263165293::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1551263164133) ENABLED START*/
        return false;
        /*PROTECTED REGION END*/

    }

    //State: PlanActions in Plan: Planning

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : found action sequence to reach goal 
     *
     * Plans in State: 				
     *   - Plan - (Name): GenerateActionsDefault, (PlanID): 1551695113275 
     *
     * Tasks: 
     *   - DefaultTask (1414681164704) (Entrypoint: 1551262808913)
     *
     * States:
     *   - DetermineGoal (1551262808912)
     *   - EvaluateGoal (1551262842117)
     *   - PlanActions (1551263139139)
     *   - EvaluateActions (1551263260517)
     *   - Perform Action (1551263346551)
     *
     * Vars:
     */
    bool TransitionCondition1551263272837::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1551263271743) ENABLED START*/
        return false;
        /*PROTECTED REGION END*/

    }

    //State: EvaluateActions in Plan: Planning

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : actions valid 
     *
     * Plans in State: 				
     *   - Plan - (Name): EvaluateActionsDefault, (PlanID): 1551695131246 
     *
     * Tasks: 
     *   - DefaultTask (1414681164704) (Entrypoint: 1551262808913)
     *
     * States:
     *   - DetermineGoal (1551262808912)
     *   - EvaluateGoal (1551262842117)
     *   - PlanActions (1551263139139)
     *   - EvaluateActions (1551263260517)
     *   - Perform Action (1551263346551)
     *
     * Vars:
     */
    bool TransitionCondition1551263629178::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1551263628215) ENABLED START*/
        return false;
        /*PROTECTED REGION END*/

    }

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : actions invalid && goal invalid 
     *
     * Plans in State: 				
     *   - Plan - (Name): EvaluateActionsDefault, (PlanID): 1551695131246 
     *
     * Tasks: 
     *   - DefaultTask (1414681164704) (Entrypoint: 1551262808913)
     *
     * States:
     *   - DetermineGoal (1551262808912)
     *   - EvaluateGoal (1551262842117)
     *   - PlanActions (1551263139139)
     *   - EvaluateActions (1551263260517)
     *   - Perform Action (1551263346551)
     *
     * Vars:
     */
    bool TransitionCondition1551263669644::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1551263668006) ENABLED START*/
        return false;
        /*PROTECTED REGION END*/

    }

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : goal valid && actions invalid 
     *
     * Plans in State: 				
     *   - Plan - (Name): EvaluateActionsDefault, (PlanID): 1551695131246 
     *
     * Tasks: 
     *   - DefaultTask (1414681164704) (Entrypoint: 1551262808913)
     *
     * States:
     *   - DetermineGoal (1551262808912)
     *   - EvaluateGoal (1551262842117)
     *   - PlanActions (1551263139139)
     *   - EvaluateActions (1551263260517)
     *   - Perform Action (1551263346551)
     *
     * Vars:
     */
    bool TransitionCondition1551695258558::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1551695257323) ENABLED START*/
        return false;
        /*PROTECTED REGION END*/

    }

    //State: Perform Action in Plan: Planning

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : received new perception 
     *
     * Plans in State: 				
     *   - Plan - (Name): PerformNextActionDefault, (PlanID): 1551695161214 
     *
     * Tasks: 
     *   - DefaultTask (1414681164704) (Entrypoint: 1551262808913)
     *
     * States:
     *   - DetermineGoal (1551262808912)
     *   - EvaluateGoal (1551262842117)
     *   - PlanActions (1551263139139)
     *   - EvaluateActions (1551263260517)
     *   - Perform Action (1551263346551)
     *
     * Vars:
     */
    bool TransitionCondition1551263634437::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1551263629562) ENABLED START*/
        return false;
        /*PROTECTED REGION END*/

    }

}
