int32 senderID
string encoding
Coordinates initialPosition
Coordinates position
Coordinates diedOn
Coordinates[] blockingWumpi
Coordinates[] blockingTraps
Coordinates[] possibleNextFields
Coordinates[] shootingTargets
int32 heading
bool haveGold
bool drafty
bool stinky
bool glitter
bool arrow
bool exhausted
bool shot
bool receivedScream
bool receivedSilence
bool exited
bool died
string objective


