#include "ConditionCreator.h"

#include  "Plans/SingleAgent/WumpusMaster1534835261527.h"

#include  "Plans/SingleAgent/InteractWithPlayground1534836538908.h"

#include  "Plans/SingleAgent/MyTurn1534836685239.h"

#include  "Plans/SingleAgent/Planning1551262808911.h"

#include  "Plans/SingleAgent/NextAction1554202530131.h"

#include  "Plans/WumpusMasterMaster1571827339498.h"

using namespace alicaAutogenerated;
namespace alica
{

    ConditionCreator::ConditionCreator()
    {
    }
    ConditionCreator::~ConditionCreator()
    {
    }

    shared_ptr<BasicCondition> ConditionCreator::createConditions(long conditionConfId)
    {
        switch (conditionConfId)
        {

            case 1536063740426:

                return make_shared<RunTimeCondition1536063740426>();

                break;

            case 1537958016407:

                return make_shared<TransitionCondition1537958016407>();

                break;

            case 1572431680595:

                return make_shared<TransitionCondition1572431680595>();

                break;

            case 1574259998405:

                return make_shared<TransitionCondition1574259998405>();

                break;

            case 1574259999562:

                return make_shared<TransitionCondition1574259999562>();

                break;

            case 1574260001551:

                return make_shared<TransitionCondition1574260001551>();

                break;

            case 1574260002562:

                return make_shared<TransitionCondition1574260002562>();

                break;

            case 1534836595527:

                return make_shared<TransitionCondition1534836595527>();

                break;

            case 1534836628585:

                return make_shared<TransitionCondition1534836628585>();

                break;

            case 1534925376501:

                return make_shared<RunTimeCondition1534925376501>();

                break;

            case 1534836737992:

                return make_shared<TransitionCondition1534836737992>();

                break;

            case 1551263121075:

                return make_shared<TransitionCondition1551263121075>();

                break;

            case 1551263161484:

                return make_shared<TransitionCondition1551263161484>();

                break;

            case 1551263165293:

                return make_shared<TransitionCondition1551263165293>();

                break;

            case 1551263272837:

                return make_shared<TransitionCondition1551263272837>();

                break;

            case 1551263629178:

                return make_shared<TransitionCondition1551263629178>();

                break;

            case 1551263634437:

                return make_shared<TransitionCondition1551263634437>();

                break;

            case 1551263669644:

                return make_shared<TransitionCondition1551263669644>();

                break;

            case 1551695258558:

                return make_shared<TransitionCondition1551695258558>();

                break;

            case 1554202971930:

                return make_shared<TransitionCondition1554202971930>();

                break;

            case 1554203054731:

                return make_shared<TransitionCondition1554203054731>();

                break;

            case 1571833039064:

                return make_shared<TransitionCondition1571833039064>();

                break;

            case 1574260068271:

                return make_shared<TransitionCondition1574260068271>();

                break;

            default:
                cerr << "ConditionCreator: Unknown condition id requested: " << conditionConfId << endl;
                throw new exception();
                break;
        }
    }
}
