#include "ConditionCreator.h"

#include  "Plans/SingleAgent/WumpusMaster1534835261527.h"

#include  "Plans/SingleAgent/InteractWithPlayground1534836538908.h"

#include  "Plans/SingleAgent/MyTurn1534836685239.h"

using namespace alicaAutogenerated;
namespace alica
{

    ConditionCreator::ConditionCreator()
    {
    }
    ConditionCreator::~ConditionCreator()
    {
    }

    shared_ptr<BasicCondition> ConditionCreator::createConditions(long conditionConfId)
    {
        switch (conditionConfId)
        {

            case 1536063740426:

                return make_shared<RunTimeCondition1536063740426>();

                break;

            case 1534836415069:

                return make_shared<TransitionCondition1534836415069>();

                break;

            case 1534836447768:

                return make_shared<TransitionCondition1534836447768>();

                break;

            case 1537958016407:

                return make_shared<TransitionCondition1537958016407>();

                break;

            case 1534836595527:

                return make_shared<TransitionCondition1534836595527>();

                break;

            case 1534836628585:

                return make_shared<TransitionCondition1534836628585>();

                break;

            case 1534925376501:

                return make_shared<RunTimeCondition1534925376501>();

                break;

            case 1534836737992:

                return make_shared<TransitionCondition1534836737992>();

                break;

            default:
                cerr << "ConditionCreator: Unknown condition id requested: " << conditionConfId << endl;
                throw new exception();
                break;
        }
    }
}
