#include "ConstraintCreator.h"
#include <iostream>

#include  "Plans/SingleAgent/constraints/WumpusMaster1534835261527Constraints.h"

#include  "Plans/SingleAgent/constraints/InteractWithPlayground1534836538908Constraints.h"

#include  "Plans/SingleAgent/constraints/MyTurn1534836685239Constraints.h"

using namespace std;
using namespace alicaAutogenerated;

namespace alica
{

    ConstraintCreator::ConstraintCreator()
    {
    }

    ConstraintCreator::~ConstraintCreator()
    {
    }

    shared_ptr<BasicConstraint> ConstraintCreator::createConstraint(long constraintConfId)
    {
        switch (constraintConfId)
        {

            default:
                cerr << "ConstraintCreator: Unknown constraint requested: " << constraintConfId << endl;
                throw new exception();
                break;
        }
    }

}
