#include <iostream>
#include "UtilityFunctionCreator.h"

#include  "Plans/SingleAgent/WumpusMaster1534835261527.h"

#include  "Plans/SingleAgent/InteractWithPlayground1534836538908.h"

#include  "Plans/SingleAgent/MyTurn1534836685239.h"

using namespace std;
using namespace alicaAutogenerated;
namespace alica
{

    UtilityFunctionCreator::~UtilityFunctionCreator()
    {
    }

    UtilityFunctionCreator::UtilityFunctionCreator()
    {
    }

    shared_ptr<BasicUtilityFunction> UtilityFunctionCreator::createUtility(long utilityfunctionConfId)
    {
        switch (utilityfunctionConfId)
        {

            case 1534835261527:
                return make_shared<UtilityFunction1534835261527>();
                break;

            case 1534836538908:
                return make_shared<UtilityFunction1534836538908>();
                break;

            case 1534836685239:
                return make_shared<UtilityFunction1534836685239>();
                break;

            default:
                cerr << "UtilityFunctionCreator: Unknown utility requested: " << utilityfunctionConfId << endl;
                throw new exception();
                break;
        }
    }

}
