#include "Plans/SingleAgent/constraints/InteractWithPlayground1534836538908Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1534836538908) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:InteractWithPlayground

/*		
 * Tasks: 
 * - EP:1534836538910 : DefaultTask (1414681164704)
 *
 * States:
 * - Wait (1534836538909)
 * - MyTurn (1534836578485)
 *
 * Vars:
 */

// State: Wait

// State: Wait

// State: MyTurn

// State: MyTurn

}
