#include "Plans/SingleAgent/constraints/MyTurn1534836685239Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1534836685239) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:MyTurn

/*		
 * Tasks: 
 * - EP:1534836698774 : DefaultTask (1414681164704)
 *
 * States:
 * - PerformAction (1534836698773)
 * - ActionPerformed (1534836725909)
 *
 * Vars:
 */

// State: PerformAction

// State: PerformAction

// State: ActionPerformed

// State: ActionPerformed

}
