#include "Plans/SingleAgent/constraints/MyTurn1534836685239Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1534836685239) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
    //Plan:MyTurn

    /*		
     * Tasks: 
     * - EP:1534836698774 : DefaultTask (1414681164704)
     *
     * States:
     * - PerformAction (1534836698773)
     * - ActionPerformed (1534836725909)
     *
     * Vars:				
     * - MyTurnPlanVar (1534925430550) 
     */

    /*
     * RuntimeCondition - (Name): NewRuntimeCondition
     * (ConditionString): 
     * Static Variables: [MyTurnPlanVar]
     * Domain Variables:

     */
    void Constraint1534925376501::getConstraint(shared_ptr<ProblemDescriptor> c, shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(cc1534925376501) ENABLED START*/
        /*PROTECTED REGION END*/
    }

// State: PerformAction

// State: PerformAction

// State: ActionPerformed

// State: ActionPerformed

}
