#include "Plans/SingleAgent/constraints/NextAction1554202530131Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1554202530131) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:NextAction

/*		
 * Tasks: 
 * - EP:1554202530133 : DefaultTask (1414681164704)
 *
 * States:
 * - DetermineObjective (1554202530132)
 * - PlanAndExecute (1554202945017)
 * - Success (1554202959483)
 *
 * Vars:
 */

// State: DetermineObjective

// State: DetermineObjective

// State: PlanAndExecute

// State: PlanAndExecute

// State: Success

// State: Success

}
