#include "Plans/SingleAgent/constraints/Planning1551262808911Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1551262808911) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:Planning

/*		
 * Tasks: 
 * - EP:1551262808913 : DefaultTask (1414681164704)
 *
 * States:
 * - DetermineGoal (1551262808912)
 * - EvaluateGoal (1551262842117)
 * - PlanActions (1551263139139)
 * - EvaluateActions (1551263260517)
 * - Perform Action (1551263346551)
 *
 * Vars:
 */

// State: DetermineGoal

// State: DetermineGoal

// State: EvaluateGoal

// State: EvaluateGoal

// State: PlanActions

// State: PlanActions

// State: EvaluateActions

// State: EvaluateActions

// State: Perform Action

// State: Perform Action

}
