#include "Plans/SingleAgent/constraints/WumpusMaster1534835261527Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1534835261527) ENABLED START*/
// Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
    //Plan:WumpusMaster

    /*		
     * Tasks: 
     * - EP:1534835261530 : DefaultTask (1414681164704)
     *
     * States:
     * - Stop (1534835261528)
     * - Play (1534836316488)
     * - AgentLeftCave (1534836405246)
     *
     * Vars:				
     * - ModelVar (1536152982013) 
     */

    /*
     * RuntimeCondition - (Name): NewRuntimeCondition
     * (ConditionString): 
     * Static Variables: [ModelVar]
     * Domain Variables:

     */
    void Constraint1536063740426::getConstraint(shared_ptr<ProblemDescriptor> c, shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(cc1536063740426) ENABLED START*/

        /*PROTECTED REGION END*/
    }

// State: Stop

// State: Stop

// State: Play

// State: Play

// State: AgentLeftCave

// State: AgentLeftCave

}
