#include "Plans/SingleAgent/constraints/WumpusMaster1534835261527Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1534835261527) ENABLED START*/
// Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
    //Plan:WumpusMaster

    /*		
     * Tasks: 
     * - EP:1534835261530 : CompleteRun (1571831044421)
     * - EP:1571748599471 : SpawnAgents (1571748498123)
     *
     * States:
     * - Wait (1534835261528)
     * - Play (1534836316488)
     * - SpawnAgents (1571748613432)
     * - Play (1572431590132)
     * - Reset (1574259961919)
     * - Reset (1574259968198)
     *
     * Vars:				
     * - ModelVar (1536152982013) 
     */

    /*
     * RuntimeCondition - (Name): NewRuntimeCondition
     * (ConditionString): 
     * Static Variables: [ModelVar]
     * Domain Variables:

     */
    void Constraint1536063740426::getConstraint(shared_ptr<ProblemDescriptor> c, shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(cc1536063740426) ENABLED START*/

        /*PROTECTED REGION END*/
    }

// State: Wait

// State: Wait

// State: Play

// State: Play

// State: SpawnAgents

// State: SpawnAgents

// State: Play

// State: Play

// State: Reset

// State: Reset

// State: Reset

// State: Reset

}
