#ifndef InteractWithPlaygroundCONSTRAINT_H_
#define InteractWithPlayground_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ProblemDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* InteractWithPlaygroundCONSTRAINT_H_ */
