#ifndef MyTurnCONSTRAINT_H_
#define MyTurn_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ProblemDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* MyTurnCONSTRAINT_H_ */
