#ifndef NextActionCONSTRAINT_H_
#define NextAction_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ProblemDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* NextActionCONSTRAINT_H_ */
