#ifndef WumpusMasterMasterCONSTRAINT_H_
#define WumpusMasterMaster_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ProblemDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* WumpusMasterMasterCONSTRAINT_H_ */
