#include "Plans/constraints/WumpusMasterMaster1571827339498Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1571827339498) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:WumpusMasterMaster

/*		
 * Tasks: 
 * - EP:1571827339500 : DefaultTask (1414681164704)
 *
 * States:
 * - Wait4Start (1571827339499)
 * - NewState (1571832997210)
 * - ExperimentComplete (1574260058143)
 *
 * Vars:
 */

// State: Wait4Start

// State: Wait4Start

// State: NewState

// State: NewState

// State: ExperimentComplete

// State: ExperimentComplete

}
