#include "Plans/WumpusMasterMaster1571827339498.h"
using namespace alica;
/*PROTECTED REGION ID(eph1571827339498) ENABLED START*/ // Add additional using directives here
#include <engine/AlicaClock.h>
#include <wumpus/WumpusWorldModel.h>
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:WumpusMasterMaster

    /* generated comment
     
     Task: DefaultTask  -> EntryPoint-ID: 1571827339500

     */
    shared_ptr<UtilityFunction> UtilityFunction1571827339498::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1571827339498) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

    //State: Wait4Start in Plan: WumpusMasterMaster

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : waited for start 
     *
     * Plans in State: 
     *
     * Tasks: 
     *   - DefaultTask (1414681164704) (Entrypoint: 1571827339500)
     *
     * States:
     *   - Wait4Start (1571827339499)
     *   - NewState (1571832997210)
     *   - ExperimentComplete (1574260058143)
     *
     * Vars:
     */
    bool TransitionCondition1571833039064::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1571833037764) ENABLED START*/
        return rp->getAssignment().getAllAgents().size() == this->wm->getPresetAgentCount();
        /*PROTECTED REGION END*/

    }

    //State: NewState in Plan: WumpusMasterMaster

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : Experiment Complete 
     *
     * Plans in State: 				
     *   - Plan - (Name): WumpusMaster, (PlanID): 1534835261527 
     *
     * Tasks: 
     *   - DefaultTask (1414681164704) (Entrypoint: 1571827339500)
     *
     * States:
     *   - Wait4Start (1571827339499)
     *   - NewState (1571832997210)
     *   - ExperimentComplete (1574260058143)
     *
     * Vars:
     */
    bool TransitionCondition1574260068271::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1574260067168) ENABLED START*/
        auto done = !this->wm->experiment->hasNextWorld() && this->wm->experiment->getCurrentRun()->isCompleted();
        if (done)
        {
            std::cout << "MasterPlan success" << std::endl;
        }
        return done;
        /*PROTECTED REGION END*/

    }

//State: ExperimentComplete in Plan: WumpusMasterMaster

}
